# configuration
OBJ_FUNCTION: 'rastrigin' # currently supported: rastrigin, sphere, ackley, griewank
IS_DISCRETE: 1
IS_ADAPT_NUM_AGENTS: 0
IS_ADAPT_PARAMETERS: 0
IS_ADAPT_ITERATIONS: 1
IS_VISUALIZE_DATA: 1

# general parameters
NUM_AGENTS: 120
ITERATIONS: 10

# adaptation - number of agents
ADAPTATION_NUM_AGENT_TAU: 1 # Softmax temperature
ADAPTATION_NUM_AGENT_MIN_CHANGE: 1 # Min number of agents to change in one cycle
ADAPTATION_NUM_AGENT_MAX_CHANGE: 8 # Max number of agents to change in one cycle
ADAPTATION_NUM_AGENT_AVG_INFLUENCE: 0.2 # Percentage describing influence of mean solution for performance calculating
ADAPTATION_NUM_AGENT_BEST_INFLUENCE: 0.8 # Percentage describing influence of best solution for performance calculating

# adaptation - parameters
ADAPTATION_PARAMETERS_EXPLORATION_PERCENTAGE: 0.3 # Percentage of all agents from specific type to increase exploration related parameters
ADAPTATION_PARAMETERS_EXPLOITATION_PERCENTAGE: 0.3 # Percentage of all agents from specific type to increase exploitation related parameters
ADAPTATION_PARAMETERS_EXPLORATION_RATE_INC: 1.2 # Weight of increasing exploration related parameters
ADAPTATION_PARAMETERS_EXPLORATION_RATE_DEC: 0.8 # Weight of decreasing exploration related parameters
ADAPTATION_PARAMETERS_EXPLOITATION_RATE_INC: 1.2 # Weight of increasing exploitation related parameters
ADAPTATION_PARAMETERS_EXPLOITATION_RATE_DEC: 0.8 # Weight of decreasing exploitation related parameters


# PSO parameters
PSO_ITERATIONS: 100
W: 0.7  # Inertion
C1: 1.4  # weight for best local position
C2: 1.8  # weight for best global position

# GA parameters
GA_ITERATIONS: 100
GA_POPULATION: 100
CROSSOVER_PROB_GA: 0.85
MUTATION_RATE_GA: 0.2
PARENTS_PERCENTAGE_GA: 0.25
CHILDREN_PERCENTAGE_GA: 0.5

# ABC parameters
ABC_ITERATIONS: 100
EMPLOYED_ABC_PERCENTAGE: 0.6
W_ABC_EMPLOYEED: 0.15  # Weight of including random phi for employed bees
W_ABC_SCOUT: 0.3  # Weight of including random phi for scout bees

# FOA parameters
FOA_ITERATIONS: 100
W_FOA: 0.05  # Weight of velocity of changes

# DE parameters
DE_ITERATIONS: 100
F_DE: 0.7  # Mutation factor
CR_DE: 0.9  # Crossover probability

# ACO parameters
ACO_ITERATIONS: 100
ALPHA_ACO: 1.0  # Inertion
BETA_ACO: 0  # Inertion
EVAPORATION_RATE_ACO: 0.2

# function parameters
DIMENSIONS: 5
DISCRETE_POINTS: 1001
MIN_VALUE: -5
MAX_VALUE: 5
